version: '2'
services:
    redis:
        image: redis
    web:
        build: .
        command: python run.py
        ports:
            - "8080:8080"
        depends_on:
            - redis
        env_file: ./envfile
